#!/bin/bash

#############################################
# DNS Server Setup Script for WSL
# Configures BIND9 for mywebapp.com domain
#############################################

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored messages
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then 
        print_error "Please run this script with sudo"
        exit 1
    fi
}

# Get the actual user (not root when using sudo)
ACTUAL_USER=${SUDO_USER:-$USER}

print_info "Starting DNS server setup for WSL..."

#############################################
# Step 1: Configure WSL settings
#############################################
print_info "Step 1: Configuring /etc/wsl.conf..."

cat > /etc/wsl.conf << 'EOF'
[user]
default=hp

[boot]
systemd=true

[network]
generateResolvConf=true
EOF

print_info "/etc/wsl.conf configured successfully"

#############################################
# Step 2: Configure resolv.conf
#############################################
print_info "Step 2: Configuring /etc/resolv.conf..."

cat > /etc/resolv.conf << 'EOF'
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
nameserver 10.255.255.254
EOF

print_info "/etc/resolv.conf configured successfully"

#############################################
# Step 3: Get server IP address
#############################################
print_info "Step 3: Detecting server IP address..."

SERVER_IP=$(ip addr show eth0 | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1)

if [ -z "$SERVER_IP" ]; then
    print_error "Could not detect server IP address from eth0"
    exit 1
fi

print_info "Detected server IP: $SERVER_IP"

#############################################
# Step 4: Install BIND9
#############################################
print_info "Step 4: Checking BIND9 installation..."

# Check if BIND9 is already installed
if dpkg -l | grep -q "^ii.*bind9 "; then
    print_info "BIND9 is already installed. Skipping installation."
else
    print_info "Installing BIND9..."
    
    if apt update && apt install -y bind9 bind9utils bind9-doc dnsutils; then
        print_info "BIND9 installed successfully"
    else
        print_error "Failed to install BIND9"
        exit 1
    fi
fi

#############################################
# Step 5: Backup existing configuration files
#############################################
print_info "Step 5: Creating backups of existing configuration..."

TIMESTAMP=$(date +%F_%T)

if [ -f /etc/bind/named.conf.options ]; then
    cp /etc/bind/named.conf.options \
       /etc/bind/named.conf.options.bak.$TIMESTAMP
    print_info "Backed up named.conf.options to named.conf.options.bak.$TIMESTAMP"
fi

if [ -f /etc/bind/named.conf.local ]; then
    cp /etc/bind/named.conf.local \
       /etc/bind/named.conf.local.bak.$TIMESTAMP
    print_info "Backed up named.conf.local to named.conf.local.bak.$TIMESTAMP"
fi

#############################################
# Step 6: Configure named.conf.local
#############################################
print_info "Step 6: Configuring /etc/bind/named.conf.local..."

cat > /etc/bind/named.conf.local << 'EOF'
//
// Do any local configuration here
//

// Forward zone for Apache web app
zone "mywebapp.com" IN {
    type master;
    file "/var/named/mywebapp.com.fzone";
    allow-query { any; };
};

//include "/etc/bind/zones.rfc1918";
EOF

print_info "named.conf.local configured successfully"

#############################################
# Step 7: Configure named.conf.options
#############################################
print_info "Step 7: Configuring /etc/bind/named.conf.options..."

cat > /etc/bind/named.conf.options << EOF
options {
    directory "/var/cache/bind";
    
    recursion yes;
    allow-query { any; };
    
    forwarders {
        8.8.8.8;
        8.8.4.4;
    };
    
    dnssec-validation auto;
    
    listen-on { 127.0.0.1; $SERVER_IP; };
    listen-on-v6 { none; };
};
EOF

print_info "named.conf.options configured with IP: $SERVER_IP"

#############################################
# Step 8: Create zone directory and file
#############################################
print_info "Step 8: Creating zone directory and zone file..."

# Create /var/named directory if it doesn't exist
mkdir -p /var/named

# Create zone file for mywebapp.com
cat > /var/named/mywebapp.com.fzone << EOF
\$TTL 86400
@   IN  SOA     ns1.mywebapp.com. admin.mywebapp.com. (
        $(date +%Y%m%d)01  ; Serial (YYYYMMDD + version)
        3600               ; Refresh
        1800               ; Retry
        604800             ; Expire
        86400 )            ; Minimum TTL

; Name servers
@       IN  NS      ns1.mywebapp.com.

; A records
@       IN  A       $SERVER_IP
ns1     IN  A       $SERVER_IP
www     IN  A       $SERVER_IP
EOF

# Set proper permissions
chown bind:bind /var/named/mywebapp.com.fzone
chmod 644 /var/named/mywebapp.com.fzone

print_info "Zone file created at /var/named/mywebapp.com.fzone"

#############################################
# Step 9: Validate configuration
#############################################
print_info "Step 9: Validating BIND configuration..."

if named-checkconf; then
    print_info "BIND configuration is valid"
else
    print_error "BIND configuration validation failed"
    exit 1
fi

# Check zone file
if named-checkzone mywebapp.com /var/named/mywebapp.com.fzone; then
    print_info "Zone file is valid"
else
    print_error "Zone file validation failed"
    exit 1
fi

#############################################
# Step 10: Restart BIND service
#############################################
print_info "Step 10: Restarting BIND9 service..."

systemctl restart named || systemctl restart bind9

# Wait a moment for service to start
sleep 2

# Check if service is running
if systemctl is-active --quiet named || systemctl is-active --quiet bind9; then
    print_info "BIND9 service is running"
else
    print_error "BIND9 service failed to start"
    systemctl status named || systemctl status bind9
    exit 1
fi

#############################################
# Step 11: Test DNS resolution
#############################################
print_info "Step 11: Testing DNS resolution..."

echo ""
print_info "Testing DNS server binding (without resolver)..."
dig @127.0.0.1 mywebapp.com +short

echo ""
print_info "Testing with resolver..."
print_info "Running: dig mywebapp.com +short"
dig mywebapp.com +short

echo ""
print_info "Running: nslookup mywebapp.com"
nslookup mywebapp.com

echo ""
print_info "Testing ping to mywebapp.com..."
ping -c 3 mywebapp.com || true

#############################################
# Summary
#############################################
echo ""
echo "============================================"
print_info "DNS Server Setup Complete!"
echo "============================================"
echo ""
echo "Configuration Summary:"
echo "  - Server IP: $SERVER_IP"
echo "  - Domain: mywebapp.com"
echo "  - Zone file: /var/named/mywebapp.com.fzone"
echo "  - DNS forwarders: 8.8.8.8, 8.8.4.4"
echo ""
echo "Backup files created:"
echo "  - /etc/bind/named.conf.options.bak.$TIMESTAMP"
echo "  - /etc/bind/named.conf.local.bak.$TIMESTAMP"
echo ""
echo "Next steps:"
echo "  1. Verify DNS resolution: dig @localhost mywebapp.com"
echo "  2. Test web access: curl http://mywebapp.com"
echo "  3. Check BIND logs: sudo journalctl -u named -f"
echo ""
print_info "Note: You may need to restart WSL for all changes to take effect"
echo "============================================"